#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2024-2026 We-Amp B.V.

# Zig C++ compiler wrapper for aarch64-linux-musl target
exec zig c++ -target aarch64-linux-musl -std=c++23 "$@"
